---
title: Annual Report
author: NPS Northeast Region Fire Effects Monitoring Program
output:
  word_document:
    toc: true
    toc_depth: 2
  pdf_document:
    toc: true
    toc_depth: 2
  html_document:
    theme: readable
    highlight: null
    toc: true
    toc_depth: 2
    toc_float:
      smooth_scroll: true
    code_download: true
---

# Annual Report

### Setup {.hidden}

```{r setup, include=FALSE}
## Markdown Options
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)

# install.packages("tidyverse")
# install.packages("kableExtra")
# install.packages("ggplot2")
```

```{r load packages, include=FALSE}
# "tidyverse" has lots of useful functions for data cleaning
library(tidyverse)
# "kableExtra" is used to produce formatted tables
library(kableExtra)
library(ggplot2)
library(stringr)
library(DT)
library(fs)
```

```{r file paths, include=FALSE}
path_main <- "Z:/NER/SHEN/RAD/Fire/Fire Mgmt/FIRE_ECOLOGIST_FILES/FFI_DATA_MANAGEMENT/"
path_data <- paste0(path_main, "Exports_Reporting/FFI/")
```

### Load Data {.hidden}

```{r load data, include=FALSE}
MetadataReport_all <- read.csv(paste0(path_data, "all_metadata.csv"))
```

### Target Year {.hidden}

```{r set parameters, include=F}
# designate target year or years 
unique(MetadataReport_all$SampleEvent_Date_Year)
target_year <- c(2026)
```

### Group By {.hidden}

```{r}
table_ProjectUnit <- MetadataReport_all %>% 
  group_by(AdminUnit_Name, Macroplot_PurposeType, Macroplot_UV1) %>% 
  dplyr::summarise(Macroplot_UV2 = paste(na.omit(unique(Macroplot_UV2)), collapse = ", "),
                   First_Year = min(SampleEvent_Date_Year),
                   Last_Year = max(SampleEvent_Date_Year),
                   Annual_Total = n_distinct(Macroplot_Name[SampleEvent_Date_Year == target_year]),
                   Total_Plots_ByProject = n_distinct(Macroplot_Name),
                   Total_Plots_ByPark = mean(n_plots_ByPurposeType),
                    .groups = "drop")

table_MonitoringType <- MetadataReport_all %>% 
  group_by(AdminUnit_Name, Macroplot_PurposeType, Macroplot_UV2) %>% 
  dplyr::summarise(Macroplot_UV1 = paste(na.omit(unique(Macroplot_UV1)), collapse = ", "),
                   First_Year = min(SampleEvent_Date_Year),
                   Last_Year = max(SampleEvent_Date_Year),
                   Annual_Total = n_distinct(Macroplot_Name[SampleEvent_Date_Year == target_year]),
                   Total_Plots_ByProject = n_distinct(Macroplot_Name),
                   Total_Plots_ByPark = mean(n_plots_ByPurposeType),
                    .groups = "drop") %>% 
  dplyr::rename(Macroplot_UV1 = Macroplot_UV2, Macroplot_UV2 = Macroplot_UV1)
```

# Table 1. Fire Effects Plot Workload

The table below summarizes all projects with plots sampled in the current year.

```{r year summ}
# Summarise yearly plot activity
table1 <- table_ProjectUnit %>% 
  filter(Annual_Total > 0) %>% 
  group_by(AdminUnit_Name, Macroplot_PurposeType) %>% 
  dplyr::summarise(Macroplot_UV1 = paste(na.omit(unique(Macroplot_UV1)), collapse = ", "),
                   Years = paste0 (min(First_Year), "-", max(Last_Year)),
                   Annual_Total = sum(as.numeric(Annual_Total)),
                   Total_Plots = mean(Total_Plots_ByPark),
                   .groups = "drop")

# Calculate totals
table1_totals <- table1 %>%
  mutate(AdminUnit_Name = "Total",
         Macroplot_PurposeType = "",
         Macroplot_UV1 = "",
         Years = "",
         Annual_Total = sum(as.numeric(Annual_Total)),
         Total_Plots = sum(as.numeric(Total_Plots))) %>% 
  arrange(AdminUnit_Name, Macroplot_PurposeType) %>% 
  slice_head()

# Bind the totals row to the original data frame
table1_w_totals <- bind_rows(table1, table1_totals)

# Rearrange and rename columns
table1_w_totals_final <- table1_w_totals %>% 
  select(AdminUnit_Name, Macroplot_UV1, Macroplot_PurposeType, Years, Annual_Total, Total_Plots) %>%
  dplyr::rename("Park" = AdminUnit_Name,
                "Plot Type" = Macroplot_PurposeType,
                "Monitoring Unit" = Macroplot_UV1,
                "Years Data Collected<br>(start-end)" = Years,
                "Annual Total<br>(current year)" = Annual_Total,
                "Total Plots<br>(at park)" = Total_Plots) %>% 
  mutate_all(as.character)

table1_w_totals_final %>%
  kbl(escape = FALSE, # to render line break in column headers
      align = "lllccc") %>%
  kable_styling(bootstrap_options = c("striped","condensed"),
                position = "left", fixed_thead = T) %>%
  row_spec(0, font_size = 14, bold = TRUE) %>%
  column_spec(3:6,extra_css = "vertical-align:middle;") %>% 
  row_spec(nrow(table1_w_totals), font_size = 14, bold = TRUE)
```

# Table B-1. All Fire Effects Plots Established

This table, found in Appendix B, summarizes the number of plots by type in each monitoring unit

```{r all plot summ, warning=FALSE}
# Summarise plot activity
tableB1 <- table_ProjectUnit %>% 
  group_by(AdminUnit_Name, Macroplot_PurposeType, Macroplot_UV1) %>%
  dplyr::summarise(Macroplot_UV2 = paste(na.omit(unique(Macroplot_UV2)), collapse = ", "),
                   Years = paste0(min(First_Year), "-", max(Last_Year)),
                   Total_Plots = mean(Total_Plots_ByProject),
                   .groups = "drop") %>% 
  #mutate(UV2 = ifelse(Macroplot_PurposeType == "FMH - Grassland", "Mixed Grassland", UV2)) %>% 
  mutate(Macroplot_UV1 = ifelse(Macroplot_UV2 != "", 
                                paste0(Macroplot_UV1, "<br>(", Macroplot_UV2, ")"), 
                                Macroplot_UV1)) %>% 
  select(!c(Macroplot_UV2))

# Calculate totals
tableB1_totals <- tableB1 %>%
  mutate(AdminUnit_Name = "Total",
         Macroplot_PurposeType = "",
         Macroplot_UV1 = "",
         Years = "",
         Total_Plots = sum(as.numeric(Total_Plots))) %>% 
  arrange(AdminUnit_Name, Macroplot_PurposeType) %>% 
  slice_head()

# Bind the totals row to the original data frame
tableB1_w_totals <- bind_rows(tableB1, tableB1_totals)

# Rearrange and rename columns
tableB1_w_totals_final <- tableB1_w_totals %>% 
  select(AdminUnit_Name, Macroplot_UV1, Macroplot_PurposeType, Years, Total_Plots) %>%
  dplyr::rename("Park" = AdminUnit_Name,
                "Plot Type" = Macroplot_PurposeType,
                "Monitoring Unit" = Macroplot_UV1,
                "Years Data Collected<br>(start-end)" = Years,
                "Total Plots<br>(at park)" = Total_Plots) %>% 
  mutate_all(as.character)

tableB1_w_totals_final %>%
  kbl(escape = FALSE, # to render line break in column headers
      align = "lllcc") %>%
  kable_styling(bootstrap_options = c("striped","condensed"),
                position = "left", fixed_thead = T) %>%
  row_spec(0, font_size = 14, bold = TRUE) %>%
  column_spec(3:5,extra_css = "vertical-align:middle;") %>% 
  row_spec(nrow(tableB1_w_totals_final), font_size = 14, bold = TRUE)
```
