---
title: "Park Report"
subtitle: Northeast Region
output:
  html_document:
    theme: readable
    highlight: null
    toc: true
    toc_depth: 2
    toc_float:
      smooth_scroll: true
    code_download: true
  pdf_document:
    toc: true
    toc_depth: 2
  word_document:
    toc: true
    toc_depth: 2
---

# Annual Report

### Setup {.hidden}

```{r}
## Markdown Options
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)
```

```{r}
## Install packages (if needed)

# install.packages("tidyverse")
# install.packages("kableExtra")
# install.packages("ggplot2")
```

```{r}
## Load Packages

# "tidyverse" has lots of useful functions for data cleaning
library(tidyverse)
# "kableExtra" is used to produce formatted tables
library(kableExtra)
library(ggplot2)
library(stringr)
library(DT)
library(fs)
library(ggplot2)
library(patchwork)
```

### Adjust File Paths {.hidden}

```{r}
## Adjust File Paths
#path_file <- "E:/Allie/FireFX_NER/FFI Data Management/R Outputs/"
path_file <- "C:/Users/alalor/OneDrive - DOI/NER/FireFX/FFI Data Management/R Outputs/"
path_data <- paste0(path_file, "ALL/Calculations/ALL_")
```

### Load Data {.hidden}

```{r}
# Load in data
MetadataReport <- read.csv(paste0(path_data, "MetadataReport.csv"))
Cover_Points <- read.csv(paste0(path_data, "Data_Cover_Points.csv"))
# Cover_SpComp <- read.csv(paste0(path_data, "Data_Cover_SpComp.csv"))
```

### Target Values {.hidden}

```{r}
target_park <- c("RICH")
target_type <- c("Grassland")
target_years <- c(2025)
year_max <- as.numeric(format(Sys.Date(), "%Y"))
date_max <- as.Date(paste0(year_max, "-12-31"))

    MetadataReport_filter <- MetadataReport %>% 
      filter(
        AdministrationUnit_Name == target_park,
        Type == target_type
        )

    Cover_filter <- Cover_Points %>% 
      filter(
        AdministrationUnit_Name == target_park,
        Type == target_type
      )

year_min <- as.numeric((min(MetadataReport_filter$SampleEventDate_Year)) - 1)
date_min <- as.Date(paste0(year_min, "-12-31"))

    MetadataReport_filter %>% 
      filter(Purpose == "Fire Monitoring Handbook") %>% 
      select(Macroplot_UV1, Macroplot_UV2) %>% 
      unique()

target_ProjectUnit <- c(
  "Malvern Hill"
  )
target_MonitoringType <- c(
  "Warm Season"
  #,"Cool Season"
  #,"Crewes Channel"
  )
```

# Graphs

## Disturbance History

```{r}
Disturbances <- MetadataReport_filter %>% 
  filter(MonStatus %in% c("Burn", "Herbicide", "Mechanical", "Mow"))

Disturbances_graph <- Disturbances %>%
  group_by(
    Region, Zone, Unit, AdministrationUnit_Name, Plot_Type, 
    DisturbanceDate, DisturbanceDate_Year, SampleEventDate_Year, MonStatus
    ) %>%
  filter(
    DisturbanceDate_Year == SampleEventDate_Year
    ) %>%
  dplyr::summarize(
    n_Macroplot = n()
    ) %>%
  mutate(
    DisturbanceDate = as.Date(DisturbanceDate),
    Macroplot_Num = "All"
    ) %>%
  arrange(desc(MonStatus))
```

```{r}
p_disturbance <- MetadataReport_filter %>%
  filter(
    Macroplot_UV1 %in% c(target_ProjectUnit),
    Macroplot_UV2 %in% c(target_MonitoringType)
    ) %>%
  ggplot(aes(x = DisturbanceDate, y = Macroplot_Num)) +
  geom_line(aes(group = Macroplot_Num),
            data = Disturbances_graph) +
  geom_point(aes(X = DisturbanceDate, y = Macroplot_Num, fill = MonStatus),
             data = Disturbances_graph, shape = 21) +
  geom_line(aes(X = DisturbanceDate, y = Macroplot_Num, fill = MonStatus),
            data = Disturbances_graph) +
  geom_point(aes(X = DisturbanceDate, y = Macroplot_Num, fill = MonStatus),
             data = Disturbances_graph, shape = 21, size = 2.5) +
  facet_grid( ~ Macroplot_UV1) +
  labs(title = "Disturbance History",
       y = "",
       x = "Year",
       fill = "") +
  scale_x_date(
    limits = c(date_min, date_max),
    date_breaks = "1 year",
    date_labels = "%Y",
    expand = expansion(mult = c(0, 0))
  ) +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.title = element_text(size = 15, face="bold", hjust = 0.5),
        axis.title = element_text(size = 12, face="bold"),
        axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
        axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust=1),
        legend.position = "top")

p_disturbance
```

## Herbs Points

```{r}
Cover_graph <- Cover_filter %>% 
  mutate(
    SampleEventDate_Year = as.numeric(SampleEventDate_Year)
    ) %>% 
  group_by(
    AdministrationUnit_Name, Purpose, Type,
    Macroplot_UV1, Macroplot_UV2, MonStatus, SampleEventDate_Year
    ,Preferred_Lifeform, Genus, Nativity, Species.Symbol
    ) %>%
  dplyr::summarise(
    n_plots = n_distinct(Macroplot),
    Avg_Ht_m = round(mean(Avg_Ht_m, na.rm = TRUE), 1),
    Avg_Ht_ft = round(mean(Avg_Ht_ft, na.rm = TRUE), 1),
    PctCover = round(mean(PctCover, na.rm = TRUE), 2),
    .groups = "drop"
    ) %>% 
  mutate(
    Preferred_Lifeform = ifelse(Preferred_Lifeform == "Undefined", "Substrate", Preferred_Lifeform),
    Preferred_Lifeform = factor(
      Preferred_Lifeform,
      levels = c(
        "Tree",
        "Shrub",
        "Subshrub",
        "Forb/herb",
        "Fern",
        "Vine",
        "Graminoid",
        "Grass-like",
        "Nonvascular", 
        "Lichenous", 
        "Substrate"
      )))
```

### Graph - 2025 Report Replicate  {.hidden}

```{r}
p_cover_classic <- Cover_graph %>% 
  filter(
    Macroplot_UV1 %in% c(target_ProjectUnit),
    Macroplot_UV2 %in% c(target_MonitoringType),
    Preferred_Lifeform %in% c(
      #"Nonvascular", "Lichenous", 
      "Graminoid", "Grass-like"
      #"Forb/herb", "Fern", "Vine",
      #"Shrub", "Subshrub",
      #"Tree",
      #"Substrate"
      ),
    Nativity %in% c(
      "Native"
      #"Non-Native",
      #"Invasive",
      #"Unknown"
      )
    ) %>% 
  group_by(
    AdministrationUnit_Name, Purpose, Type, 
    Macroplot_UV1, Macroplot_UV2, MonStatus, SampleEventDate_Year
    #,Preferred_Lifeform, Genus, Nativity
    ) %>% 
  mutate(
    Total_Cover = sum(PctCover)
    ) %>%  

  
  ggplot(aes(x = SampleEventDate_Year, y = Total_Cover)) +
  geom_line() +
  geom_point() +
  facet_wrap( ~ Macroplot_UV2, ncol = 1) +
  labs(
    x = "Year",
    y = "% Cover",
    title = paste(target_park, target_type, "Native Grass Cover")
    ) +
  scale_x_continuous(
    limits = c(year_min, year_max),
    breaks = seq(year_min, year_max, by = 1),
    expand = expansion(mult = c(0, 0))
    ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 8, angle = 90, hjust = 0.5, vjust = 0.5),
    plot.title = element_text(size = 15, face="bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, face="bold", hjust = 0.5),
    axis.title = element_text(size = 12, face="bold"),
    axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
    axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
    axis.text.y = element_text(size = 8),
    panel.grid.minor = element_blank()
    )

p_cover_classic
```

### Graph - Cover Native Grass {.hide-header}

```{r}
p_cover_points <- Cover_graph %>% 
  filter(
    Macroplot_UV1 %in% c(target_ProjectUnit),
    Macroplot_UV2 %in% c(target_MonitoringType),
    Preferred_Lifeform %in% c(
      #"Nonvascular", "Lichenous", 
      "Graminoid", "Grass-like"
      #"Forb/herb", "Fern", "Vine",
      #"Shrub", "Subshrub",
      #"Tree",
      #"Substrate"
      ),
    Nativity %in% c(
      "Native"
      #"Non-Native",
      #"Invasive",
      #"Unknown"
      )
    ) %>% 
  group_by(
    AdministrationUnit_Name, Purpose, Type, 
    Macroplot_UV1, Macroplot_UV2, MonStatus, SampleEventDate_Year
    ,Preferred_Lifeform
    ,Genus
    ,Nativity
    ,Species.Symbol
    ) %>% 
  dplyr::summarise(
    Total_Cover = sum(PctCover, na.rm = TRUE),
    .groups = "drop"
    ) %>%  
  
  ggplot(aes(
      x = SampleEventDate_Year, 
      y = Total_Cover, 
      fill = Genus
      )) +
  geom_col() +
  facet_wrap( ~ Macroplot_UV2, ncol = 1) +
  labs(
    x = "Year",
    y = "% Cover",
    title = paste(target_park, target_type, "Native Grass Cover")
    ) +
  scale_x_continuous(
    limits = c(year_min, year_max),
    breaks = seq(year_min, year_max, by = 1),
    expand = expansion(mult = c(0, 0))
    ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 8, angle = 90, hjust = 0.5, vjust = 0.5),
    plot.title = element_text(size = 15, face="bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, face="bold", hjust = 0.5),
    axis.title = element_text(size = 12, face="bold"),
    axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
    axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
    axis.text.y = element_text(size = 8),
    panel.grid.minor = element_blank()
    ) +
  geom_vline(
    xintercept = (MetadataReport_filter$DisturbanceDate_Year) - 0.5, 
    linetype = "dashed", 
    color = "red"
    )

#p_cover_points
```

```{r}
p_disturbance_merge <- p_disturbance +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "right",
        plot.margin = margin(t = 5, r = 5, b = 0, l = 5)
        )+
  labs(
    title = paste(target_park, target_type, "Native Grass Cover"),
    fill = "Disturbance"
       )

p_cover_merge <- p_cover_points +
  theme(plot.title = element_blank())

p_disturbance_merge / p_cover_merge +
  plot_layout(heights = c(0.2, 1.4))
```

### Graph - Cover Lifeform {.hide-header}

```{r}
p_cover_lifeform <- Cover_graph %>% 
  filter(
    Macroplot_UV1 %in% c(target_ProjectUnit),
    Macroplot_UV2 %in% c(target_MonitoringType),
    Preferred_Lifeform %in% c(
      #"Nonvascular", "Lichenous", 
      "Graminoid", "Grass-like",
      "Forb/herb", "Fern", 
      #"Vine",
      "Shrub", "Subshrub"
      #"Tree",
      #"Substrate"
      ),
    Nativity %in% c(
      "Native",
      "Non-Native",
      "Invasive",
      "Unknown"
      )
    ) %>% 
  group_by(
    AdministrationUnit_Name, Purpose, Type, 
    Macroplot_UV1, Macroplot_UV2, MonStatus, SampleEventDate_Year
    ,Preferred_Lifeform
    ,Genus
    ,Nativity
    ,Species.Symbol
    ) %>% 
  dplyr::summarise(
    Total_Cover = sum(PctCover, na.rm = TRUE),
    .groups = "drop"
    ) %>%  
  
  ggplot(aes(
      x = SampleEventDate_Year, 
      y = Total_Cover, 
      fill = Preferred_Lifeform
      )) +
  geom_col() +
  facet_wrap( ~ Macroplot_UV2, ncol = 1) +
  labs(
    x = "Year",
    y = "% Cover",
    fill = "Lifeform",
    title = paste(target_park, target_type, "Cover")
    ) +
  scale_x_continuous(
    limits = c(year_min, year_max),
    breaks = seq(year_min, year_max, by = 1),
    expand = expansion(mult = c(0, 0))
    ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 8, angle = 90, hjust = 0.5, vjust = 0.5),
    plot.title = element_text(size = 15, face="bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, face="bold", hjust = 0.5),
    axis.title = element_text(size = 12, face="bold"),
    axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
    axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
    axis.text.y = element_text(size = 8),
    panel.grid.minor = element_blank()
    ) +
  geom_vline(
    xintercept = (MetadataReport_filter$DisturbanceDate_Year) - 0.5, 
    linetype = "dashed", 
    color = "red"
    )

#p_cover_lifeform
```

```{r}
p_disturbance_merge <- p_disturbance +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "right",
        plot.margin = margin(t = 5, r = 5, b = 0, l = 5)
        )+
  labs(
    title = paste(target_park, target_type, "Cover"),
    fill = "Disturbance"
       )

p_cover_merge <- p_cover_lifeform +
  theme(plot.title = element_blank())

p_disturbance_merge / p_cover_merge +
  plot_layout(heights = c(0.2, 1.4))
```

### Graph - Cover Nativity {.hide-header}

```{r}
p_cover_nativity <- Cover_graph %>% 
  filter(
    Macroplot_UV1 %in% c(target_ProjectUnit),
    Macroplot_UV2 %in% c(target_MonitoringType),
    Preferred_Lifeform %in% c(
      "Nonvascular", "Lichenous", 
      "Graminoid", "Grass-like",
      "Forb/herb", "Fern", "Vine",
      "Shrub", "Subshrub",
      "Tree"
      #"Substrate"
      ),
    Nativity %in% c(
      "Native",
      "Non-Native",
      "Invasive"
      #"Unknown"
      )
    ) %>% 
  group_by(
    AdministrationUnit_Name, Purpose, Type, 
    Macroplot_UV1, Macroplot_UV2, MonStatus, SampleEventDate_Year
    ,Preferred_Lifeform
    ,Genus
    ,Nativity
    ,Species.Symbol
    ) %>% 
  dplyr::summarise(
    Total_Cover = sum(PctCover, na.rm = TRUE),
    .groups = "drop"
    ) %>%  
  
  ggplot(aes(
      x = SampleEventDate_Year, 
      y = Total_Cover, 
      fill = Nativity
      )) +
  geom_col() +
  facet_wrap( ~ Macroplot_UV2, ncol = 1) +
  labs(
    x = "Year",
    y = "% Cover",
    fill = "Lifeform",
    title = paste(target_park, target_type, "Native Cover")
    ) +
  scale_x_continuous(
    limits = c(year_min, year_max),
    breaks = seq(year_min, year_max, by = 1),
    expand = expansion(mult = c(0, 0))
    ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 8, angle = 90, hjust = 0.5, vjust = 0.5),
    plot.title = element_text(size = 15, face="bold", hjust = 0.5),
    plot.subtitle = element_text(size = 10, face="bold", hjust = 0.5),
    axis.title = element_text(size = 12, face="bold"),
    axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
    axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
    axis.text.y = element_text(size = 8),
    panel.grid.minor = element_blank()
    ) +
  geom_vline(
    xintercept = (MetadataReport_filter$DisturbanceDate_Year) - 0.5, 
    linetype = "dashed", 
    color = "red"
    )

#p_cover_nativity
```

```{r}
p_disturbance_merge <- p_disturbance +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "right",
        plot.margin = margin(t = 5, r = 5, b = 0, l = 5)
        )+
  labs(
    title = paste(target_park, target_type, "Native Cover"),
    fill = "Disturbance"
       )

p_cover_merge <- p_cover_nativity +
  theme(plot.title = element_blank())

p_disturbance_merge / p_cover_merge +
  plot_layout(heights = c(0.2, 1.4))
```

## Herbs Species Comp

```{r}
# HerbsSpComp_graph <- HerbsSpComp_all %>% 
#   filter(AdministrationUnit_Name == target_park,
#          Type == target_type) %>% 
#   group_by(AdministrationUnit_Name, Plot_Type, MacroPlot.UV1, MonStatus, SampleEventDate_Year, Nativity) %>% 
#   dplyr::summarise(n_species_ByNativity = n_distinct(Species.Symbol),
#                    .groups = "drop")
```

```{r}
# HerbsSpComp_graph %>%
#   ggplot(aes(x = SampleEventDate_Year, y = n_species_ByNativity, fill = Nativity)) +
#   geom_bar(position = "stack", stat = "identity")
```
