---
title: "FMH Data Analysis"
author: "Alexandra Lalor"
output:
  html_document:
    theme: readable
    highlight: 
    toc: yes
    toc_depth: 3
    toc_float:
      smooth_scroll: yes
    code_download: true
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

# BEFORE STARTING

### Install Packages (if needed)

```{r}
# install.packages("tidyverse")
# install.packages("Rtools")
# install.packages("janitor")
# install.packages("condformat")
# install.packages("knitr")
# install.packages("here")
# install.packages("EnvStats")
```

### Load Packages

```{r}
# tidyverse and dplyr have lots of useful functions for data cleaning
library(tidyverse)
library(dplyr)
library(plyr)
# janitor has functions to find duplicates
library(janitor)
# EnvStats is needed for the rosnerTest() function
library(EnvStats)
# writexl is used to create excel output files
library(writexl)
# condformat is used to format excel output files
library(condformat)
# knitr is used to create output files from R Markdown
library(knitr)
# here is useful for easily finding the working directory of any project
library(here)
```

### Set Target Values

```{r}
# designate target park(s)
target_park <- "SHEN"
target_project <- "BigMeadows"
# designate target year or years
years <- c(2025)
```

### Adjust File Paths

Make sure to update file paths to be specific for your data.

```{r}
# Identify working directory.
here()

# Load in data.
#path_file <- "E:/Allie/R/NER/data/"
path_file <- "C:/Users/alalor/OneDrive - DOI/NER/FireFX/FFI Data Management/R Outputs/"
path_data <- paste0(path_file, target_park, "/", target_project, "_")
```

### Load Data

```{r}
# Load in data
Fuels1000_all <- read.csv(paste0(path_data, "Surface Fuels - 1000Hr_XPT.csv"), quote = "")
FuelsDuffLitt_all <- read.csv(paste0(path_data, "Surface Fuels - Duff_Litter_XPT.csv"), quote = "")
FuelsFine_all <- read.csv(paste0(path_data, "Surface Fuels - Fine_XPT.csv"), quote = "")
PostBurn_all <- read.csv(paste0(path_data, "Post Burn Severity (metric)_XPT.csv"), quote = "")
Trees_all <- read.csv(paste0(path_data, "Trees - Individuals (metric)_XPT.csv"), quote = "")
Seedlings_all <- read.csv(paste0(path_data, "Density - Quadrats (metric)_XPT.csv"), quote = "")
Shrubs_all <- read.csv(paste0(path_data, "Density - Belts (metric)_XPT.csv"), quote = "")
HerbsObs_all <- read.csv(paste0(path_data, "Cover - Species Composition (metric)_XPT.csv"), quote = "")
HerbsPoints_all <- read.csv(paste0(path_data, "Cover - Points (metric)_XPT.csv"), quote = "")
```

### Clean Data

```{r}
#####
# Fuels1000
#####
# Reformat date column
Fuels1000_all <- Fuels1000_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# FuelsDuffLitt
#####
# Reformat date column
FuelsDuffLitt_all <- FuelsDuffLitt_all %>%  
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# FuelsFine
#####
# Reformat date column
FuelsFine_all <- FuelsFine_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# PostBurn
#####
# Reformat date column
PostBurn_all <- PostBurn_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# Trees
#####
# Reformat date column
Trees_all <- Trees_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# Seedlings
#####
# Reformat date column
Seedlings_all <- Seedlings_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# Shrubs
#####
# Reformat date column
Shrubs_all <- Shrubs_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# HerbsObs
#####
# Reformat date column
HerbsObs_all <- HerbsObs_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))

#####
# HerbsPoints
#####
# Reformat date column
HerbsPoints_all <- HerbsPoints_all %>%
  # Separate Date column
  separate(Date, sep = " ", into = c("Date", "Time")) %>%
  separate(Date, sep = "/", into = c("Month", "Day", "Year"), remove = FALSE) %>%
  # Reformat Date column
  mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
  # Remove Month, Day, and Time columns
  select(!c("Month", "Day", "Time"))
```

### Filter Data

```{r}
#####
# Fuels1000
#####
# Ensure blanks in Visited column are NA
Fuels1000_all$Visited[Fuels1000_all$Visited==""] <- NA
# Fuels1000 data
Fuels1000_data <- Fuels1000_all %>%
  filter(is.na(Visited), Year %in% years)
# Fuels1000 headers
Fuels1000_header <- Fuels1000_all %>%
  filter(!is.na(Visited), Year %in% years)

#####
# FuelsDuffLitt
#####
# Ensure blanks in Visited column are NA 
FuelsDuffLitt_all$Visited[FuelsDuffLitt_all$Visited==""] <- NA 
# FuelsDuffLitt data
FuelsDuffLitt_data <- FuelsDuffLitt_all %>%   
  filter(is.na(Visited), Year %in% years)  
# FuelsDuffLitt headers 
FuelsDuffLitt_header <- FuelsDuffLitt_all %>%   
  filter(!is.na(Visited), Year %in% years)

#####
# FuelsFine
#####
# Ensure blanks in Visited column are NA 
FuelsFine_all$Visited[FuelsFine_all$Visited==""] <- NA  
# FuelsFine data
FuelsFine_data <- FuelsFine_all %>%   
  filter(is.na(Visited), Year %in% years)  
# FuelsFine headers 
FuelsFine_header <- FuelsFine_all %>%   
  filter(!is.na(Visited), Year %in% years)

#####
# PostBurn
#####
# Ensure blanks in Visited column are NA
PostBurn_all$Visited[PostBurn_all$Visited==""] <- NA
# PostBurn data
PostBurn_data <- PostBurn_all %>%
  filter(is.na(Visited), Year %in% years)
# PostBurn headers
PostBurn_header <- PostBurn_all %>%
  filter(!is.na(Visited), Year %in% years)

#####
# Trees
#####
# Ensure blanks in Visited column are NA 
Trees_all$Visited[Trees_all$Visited==""] <- NA  
# Trees data
Trees_data <- Trees_all %>%   
  filter(is.na(Visited), Year %in% years)  
# Trees headers
Trees_header <- Trees_all %>%   
  filter(!is.na(Visited), Year %in% years)

#####
# Seedlings
#####
# Ensure blanks in Visited column are NA
Seedlings_all$Visited[Seedlings_all$Visited==""] <- NA
# Seedlings data
Seedlings_data <- Seedlings_all %>%
  filter(is.na(Visited), Year %in% years)
# Seedlings headers
Seedlings_header <- Seedlings_all %>%
  filter(!is.na(Visited), Year %in% years)

#####
# Shrubs
#####
# Ensure blanks in Visited column are NA
Shrubs_all$Visited[Shrubs_all$Visited==""] <- NA
# Shrubs data
Shrubs_data <- Shrubs_all %>%
  filter(is.na(Visited), Year %in% years)
# Shrubs headers
Shrubs_header <- Shrubs_all %>%
  filter(!is.na(Visited), Year %in% years)

#####
# HerbsObs
#####
# Ensure blanks in Visited column are NA
HerbsObs_all$Visited[HerbsObs_all$Visited==""] <- NA
# HerbsObs data
HerbsObs_data <- HerbsObs_all %>%
  filter(is.na(Visited), Year %in% years)
# HerbsObs headers
HerbsObs_header <- HerbsObs_all %>%
  filter(!is.na(Visited), Year %in% years)

#####
# HerbsPoints
#####
# Ensure blanks in Visited column are NA
HerbsPoints_all$Visited[HerbsPoints_all$Visited==""] <- NA
# HerbsPoints data
HerbsPoints_data <- HerbsPoints_all %>%
  filter(is.na(Visited), Year %in% years)
# HerbsPoints headers
HerbsPoints_header <- HerbsPoints_all %>%
  filter(!is.na(Visited), Year %in% years)
```

# ANALYSIS

```{r}
Trees_data_graph <- Trees_data %>% 
  mutate(Status = toupper(Status)) %>% 
  mutate(NoDead = count())
```

```{r}
graph_sum_Disturbances %>% 
  filter(AdministrationUnit_Name == "RICH") %>% 
  ggplot(aes(x = DisturbanceDate, y = Disturbance_Type)) +
  geom_line(aes(group = Disturbance_Type)) +
  geom_point(aes(fill = Disturbance_Type), shape = 21) +
  facet_grid(Type ~ AdministrationUnit_Name) +
  #geom_text(size = 4) +
  #geom_label_repel(aes(size = 4)) +
  labs(title = "Disturbance History",
       y = "Park",
       x = "Year",
       fill = "Disturbance Type") +
  #scale_fill_manual(values=c('yellowgreen', "yellow", 'orange', "red", "darkred","grey")) +
  scale_x_date(date_labels = "%Y", date_breaks = "1 year") +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        plot.title = element_text(size = 20, face="bold", hjust = 0.5),
        axis.title = element_text(size = 12, face="bold"),
        axis.title.y = element_text(margin = unit(c(0,4,0,0), "mm")),
        axis.title.x = element_text(margin = unit(c(4,0,0,0), "mm")),
        axis.text.y = element_text(size = 8),
        axis.text.x = element_text(size = 8, angle = 90, vjust = 0.5, hjust=1))
```

```{r}
Trees_data_graph %>% 
  ggplot(aes(x = MacroPlot.Name, y = )) %>% 
  geom_bar(aes(group = Status))
```
