---
title: Clean and Merge FFI Data
author: Alexandra Lalor
output:
  word_document:
    toc: true
    toc_depth: 2
  pdf_document:
    toc: true
    toc_depth: 2
  html_document:
    theme: readable
    highlight: null
    toc: true
    toc_depth: 2
    toc_float:
      smooth_scroll: true
    code_download: true
---

# Purpose

This code is intended to combine data depot exports from multiple parks into a single file.

## Before Starting {.hidden}

### Setup {.hidden}

```{r setup, include=FALSE}
## Markdown Options
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)
```

```{r}
## Install packages (if needed)

# install.packages("tidyverse")
```

```{r}
## Load Packages

# "tidyverse" has lots of useful functions for data cleaning
library(tidyverse)
library(stringr)
```

### Target Park

```{r}
parks <- c("ANTI", "APCO", "CATO", "CUVA", "DEWA", "FRSP", "GATE", "GETT", "MONO", "NERI", "PRWI", "RICH", "SARA", "SHEN", "VAFO")
```

### Adjust File Paths {.hidden}

```{r}
# adjust file paths
#path_main <- "E:/Allie/FireFX_NER/FFI Data Management/"
path_main <- "C:/Users/alalor/OneDrive - DOI/NER/FireFX/FFI Data Management/"
path_main_data <- paste0(path_main, "Exports/DataDepot/")
path_main_save <- paste0(path_main, "Exports_Clean/DataDepot/")
```

# Metadata

```{r warning=FALSE}
protocols <- c("project_units", "species_info")

for (p in protocols) {
  
# reset for each protocol
final_df <- NULL

  for(i in parks) {
    # select target park
    target_park <- i
    
    
    # adjust file paths
    path_data <- paste0(path_main_data, target_park, "/Metric_ffi_", target_park, "_data_export/")
    path_save <- paste0(path_main_save, "all_")
    
    
    # load data
    temp_df <- read.csv(paste0(path_data, "ffi_", target_park, "_data_export_", p, ".csv"), na.strings = c("","NA","N/A"))
    
    
    # clean data
    temp_df <- temp_df %>%
      # remove trailing/leading whitespace
      mutate(across(where(is.character), str_trim)) %>% 
      # remove line breaks
      mutate(across(where(is.character), ~ gsub("[\r\n]+", " ", .))) %>% 
      # add column
      add_column(AdminUnit_Name = target_park, .before = 1)
    ## replace commas with semicolons
    temp_df[] <- lapply(temp_df, function(x) gsub(",", ";", x))
    ## replace double quotes with single quotes
    temp_df[] <- lapply(temp_df, function(x) gsub('"', "'", x))
    
    
    # add data to master list
    final_df <- rbind(final_df, temp_df)
  }

#save file
write.csv(final_df, paste0(path_save, p, ".csv"), quote = FALSE, row.names = FALSE)

}
```

# Protocols

```{r warning=FALSE}
protocols <- c(
  "cover_line_intercept", #"cover_frequency", 
  "cover_points", "cover_species_composition", 
  "surface_fuels_alaska_duff_litter", "surface_fuels_duff_litter",
  "surface_fuels_fine", "surface_fuels_thousand_hr",
  "surface_fuels_piles", "surface_fuels_vegetation",
  "trees_individuals", "trees_saplings", "trees_seedlings"
  )

#############
## METRIC  ##
#############

for (p in protocols) {
  
# reset for each protocol
final_df <- NULL

  for(i in parks) {
    # select target park
    target_park <- i
    
    
    # adjust file paths
    path_data <- paste0(path_main_data, target_park, "/Metric_ffi_", target_park, "_data_export/")
    path_save <- paste0(path_main_save, "metric_")
    
    
    # load data
    temp_df <- read.csv(paste0(path_data, "ffi_", target_park, "_data_export_", p, ".csv"), na.strings = c("","NA","N/A"))
    
    
    # clean data
    temp_df <- temp_df %>%
      # remove trailing/leading whitespace
      mutate(across(where(is.character), str_trim)) %>% 
      # remove line breaks
      mutate(across(where(is.character), ~ gsub("[\r\n]+", " ", .)))
    ## replace commas with semicolons
    temp_df[] <- lapply(temp_df, function(x) gsub(",", ";", x))
    ## replace double quotes with single quotes
    temp_df[] <- lapply(temp_df, function(x) gsub('"', "'", x))
  
    
    # add data to master list
    final_df <- rbind(final_df, temp_df)
  }

# final column renaming to match protocol exports
final_df <- final_df %>%
  # relocate columns
    relocate(Macroplot_Datum, .after = Macroplot_UtmZone) %>%
    relocate(Macroplot_FutureVisit, .after = Macroplot_DateOut) %>%
    relocate(Macroplot_LocatedBy, .before = Macroplot_StartPoint) %>%
  # rename columns
  dplyr::rename(
    Macroplot_Lat_dd = Macroplot_DdLat,
    Macroplot_Long_dd = Macroplot_DdLong,
    Macroplot_UtmX_m = Macroplot_UtmX..m.,
    Macroplot_UtmY_m = Macroplot_UtmY..m.,
    Macroplot_SlopeHill_pct = Macroplot_SlopeHill....,
    Macroplot_SlopeTransect_pct = Macroplot_SlopeTransect....,
  ) %>%
  # final column selections
  select(!c(OrganizationId, AdminUnitId, MacroplotId, 
            SampleEventId, MethodId, MethodDataId, MethodData_Id))

names(final_df) <- sub("\\..*", "", names(final_df))

# save file
write.csv(final_df, paste0(path_save, p, ".csv"), quote = FALSE, row.names = FALSE)

}

##############
## ENGLISH  ##
##############

for (p in protocols) {
  
# reset for each protocol
final_df <- NULL

  for(i in parks) {
    # select target park
    target_park <- i
    
    
    # adjust file paths
    path_data <- paste0(path_main_data, target_park, "/English_ffi_", target_park, "_data_export/")
    path_save <- paste0(path_main_save, "english_")
    
    
    # load data
    temp_df <- read.csv(paste0(path_data, "ffi_", target_park, "_data_export_", p, ".csv"), na.strings = c("","NA","N/A"))
    
    
    # clean data
    temp_df <- temp_df %>%
      # remove trailing/leading whitespace
      mutate(across(where(is.character), str_trim)) %>% 
      # remove line breaks
      mutate(across(where(is.character), ~ gsub("[\r\n]+", " ", .)))
    ## replace commas with semicolons
    temp_df[] <- lapply(temp_df, function(x) gsub(",", ";", x))
    ## replace double quotes with single quotes
    temp_df[] <- lapply(temp_df, function(x) gsub('"', "'", x))
  
    
    # add data to master list
    final_df <- rbind(final_df, temp_df)
  }

# final column renaming to match protocol exports
final_df <- final_df %>%
  # relocate columns
    relocate(Macroplot_Datum, .after = Macroplot_UtmZone) %>%
    relocate(Macroplot_FutureVisit, .after = Macroplot_DateOut) %>%
    relocate(Macroplot_LocatedBy, .before = Macroplot_StartPoint) %>%
  # rename columns
  dplyr::rename(
    Macroplot_Lat_dd = Macroplot_DdLat,
    Macroplot_Long_dd = Macroplot_DdLong,
    Macroplot_UtmX_m = Macroplot_UtmX..m.,
    Macroplot_UtmY_m = Macroplot_UtmY..m.,
    Macroplot_SlopeHill_pct = Macroplot_SlopeHill....,
    Macroplot_SlopeTransect_pct = Macroplot_SlopeTransect....,
  ) %>%
  # final column selections
  select(!c(OrganizationId, AdminUnitId, MacroplotId, 
            SampleEventId, MethodId, MethodDataId, MethodData_Id))

names(final_df) <- sub("\\..*", "", names(final_df))

# save file
write.csv(final_df, paste0(path_save, p, ".csv"), quote = FALSE, row.names = FALSE)

}
```
