---
title: "SHEN Report"
subtitle: Northeast Region
output:
  word_document:
    toc: true
    toc_depth: 2
  pdf_document:
    toc: true
    toc_depth: 2
  html_document:
    theme: readable
    highlight: null
    toc: true
    toc_depth: 2
    toc_float:
      smooth_scroll: true
    code_download: true
---

# Annual Report

### Setup {.hidden}

```{r}
## Markdown Options
knitr::opts_chunk$set(echo = FALSE, error = FALSE, warning = FALSE, message = FALSE)
```

```{r}
## Install packages (if needed)

# install.packages("tidyverse")
# install.packages("kableExtra")
# install.packages("ggplot2")
```

```{r}
## Load Packages

# "tidyverse" has lots of useful functions for data cleaning
library(tidyverse)
# "kableExtra" is used to produce formatted tables
library(kableExtra)
library(ggplot2)
library(stringr)
library(DT)
library(fs)
library(ggplot2)
```

### Target Park

```{r}
target_park <- "SHEN"
target_years <- c(2025)
target_project <- "Big Meadows West"
```

### Adjust File Paths

```{r}
## Adjust File Paths
path_file <- "E:/Allie/FireFX_NER/FFI Data Management/R Outputs/"
#path_file <- "C:/Users/alalor/OneDrive - DOI/NER/FireFX/FFI Data Management/R Outputs/"
path_data <- paste0(path_file, target_park, "/", target_park, "_")
```

### Load Data {.hidden}

```{r}
# Load in data
MetadataReport <- read.csv(paste0(path_data, "MetadataReport.csv"))
SpeciesReport <- read.csv(paste0(path_data, "SpeciesReport.csv"))
Fuels1000 <- read.csv(paste0(path_data, "Data_Surface Fuels - 1000Hr.csv"))
FuelsDuffLitt <- read.csv(paste0(path_data, "Data_Surface Fuels - Duff_Litter.csv"))
FuelsFine <- read.csv(paste0(path_data, "Data_Surface Fuels - Fine.csv"))
PostBurn <- read.csv(paste0(path_data, "Data_Post Burn Severity (metric).csv"))
Trees <- read.csv(paste0(path_data, "Data_Trees - Individuals (metric).csv"))
Seedlings <- read.csv(paste0(path_data, "Data_Density - Quadrats (metric).csv"))
Shrubs <- read.csv(paste0(path_data, "Data_Density - Belts (metric).csv"))
HerbsSpComp <- read.csv(paste0(path_data, "Data_Cover - Species Composition (metric).csv"))
HerbsPoints <- read.csv(paste0(path_data, "Data_Cover - Points (metric).csv"))
```

### Filter Data

```{r}
#####
# Fuels1000
#####
# Fuels1000 data
Fuels1000_data <- Fuels1000 %>%
  filter(Date_Year %in% target_years)

#####
# FuelsDuffLitt
#####
# FuelsDuffLitt data
FuelsDuffLitt_data <- FuelsDuffLitt %>%   
  filter(Date_Year %in% target_years)  

#####
# FuelsFine
#####
# FuelsFine data
FuelsFine_data <- FuelsFine %>%   
  filter(Date_Year %in% target_years)  

#####
# PostBurn
#####
# PostBurn data
PostBurn_data <- PostBurn %>%
  filter(Date_Year %in% target_years)

#####
# Trees
#####
# Trees data
Trees_data <- Trees %>%   
  filter(Date_Year %in% target_years)  

#####
# Seedlings
#####
# Seedlings data
Seedlings_data <- Seedlings %>%
  filter(Date_Year %in% target_years)

#####
# Shrubs
#####
# Shrubs data
Shrubs_data <- Shrubs %>%
  filter(Date_Year %in% target_years)

#####
# HerbsSpComp
#####
# HerbsSpComp data
HerbsSpComp_data <- HerbsSpComp %>%
  filter(Date_Year %in% target_years)

#####
# HerbsPoints
#####
# HerbsPoints data
HerbsPoints_data <- HerbsPoints %>%
  filter(Date_Year %in% target_years)
```

# Background

# Methods

# Monitoring Objective Table

# Results Summary

# Graphs

```{r}
test <- HerbsSpComp %>% 
  group_by(SampleEvent_TreatmentUnit, MacroPlot.Name) %>% 
  mutate(n_plants = n_distinct(Species.Symbol))
```

# Discussion
